name: RPG
version: 1.0
main: org.role.rPG.RPG
api-version: '1.21'
depend:
  - packetevents
softdepend: [PlaceholderAPI]
commands:
  myinfo:
    description: 내 정보 UI를 엽니다.
    usage: /myinfo
  sucheck:
    description: 자신의 돈을 소모하여 지정한 금액의 수표를 발행합니다.
    usage: /수표 <금액> [개수]
    aliases: [수표]
  devsucheck:
    description: 돈 소모 없이 지정한 금액의 수표를 발행합니다.
    usage: /개발자수표 <금액> [개수]
    aliases: [개발자수표]
  메뉴:
    usage: /메뉴
  rpgitem:
    usage: /rpgitem
  리포지:
    usage: /리포지
  mob:
    description: 커스텀 몹을 관리합니다.
    usage: /mob <spawn|remove> <mob_id>